package com.jiac.server.domain;

public class CourseContentFile {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_content_file.id
     *
     * @mbg.generated Thu Jan 14 13:29:37 GMT+08:00 2021
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_content_file.course_id
     *
     * @mbg.generated Thu Jan 14 13:29:37 GMT+08:00 2021
     */
    private String courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_content_file.url
     *
     * @mbg.generated Thu Jan 14 13:29:37 GMT+08:00 2021
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_content_file.name
     *
     * @mbg.generated Thu Jan 14 13:29:37 GMT+08:00 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_content_file.size
     *
     * @mbg.generated Thu Jan 14 13:29:37 GMT+08:00 2021
     */
    private Integer size;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_content_file.id
     *
     * @return the value of course_content_file.id
     *
     * @mbg.generated Thu Jan 14 13:29:37 GMT+08:00 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_content_file.id
     *
     * @param id the value for course_content_file.id
     *
     * @mbg.generated Thu Jan 14 13:29:37 GMT+08:00 2021
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_content_file.course_id
     *
     * @return the value of course_content_file.course_id
     *
     * @mbg.generated Thu Jan 14 13:29:37 GMT+08:00 2021
     */
    public String getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_content_file.course_id
     *
     * @param courseId the value for course_content_file.course_id
     *
     * @mbg.generated Thu Jan 14 13:29:37 GMT+08:00 2021
     */
    public void setCourseId(String courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_content_file.url
     *
     * @return the value of course_content_file.url
     *
     * @mbg.generated Thu Jan 14 13:29:37 GMT+08:00 2021
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_content_file.url
     *
     * @param url the value for course_content_file.url
     *
     * @mbg.generated Thu Jan 14 13:29:37 GMT+08:00 2021
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_content_file.name
     *
     * @return the value of course_content_file.name
     *
     * @mbg.generated Thu Jan 14 13:29:37 GMT+08:00 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_content_file.name
     *
     * @param name the value for course_content_file.name
     *
     * @mbg.generated Thu Jan 14 13:29:37 GMT+08:00 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_content_file.size
     *
     * @return the value of course_content_file.size
     *
     * @mbg.generated Thu Jan 14 13:29:37 GMT+08:00 2021
     */
    public Integer getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_content_file.size
     *
     * @param size the value for course_content_file.size
     *
     * @mbg.generated Thu Jan 14 13:29:37 GMT+08:00 2021
     */
    public void setSize(Integer size) {
        this.size = size;
    }
}