package com.jiac.server.domain;

import java.math.BigDecimal;
import java.util.Date;

public class CourseInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_info.id
     *
     * @mbg.generated Sun Jan 10 16:07:36 GMT+08:00 2021
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_info.name
     *
     * @mbg.generated Sun Jan 10 16:07:36 GMT+08:00 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_info.summary
     *
     * @mbg.generated Sun Jan 10 16:07:36 GMT+08:00 2021
     */
    private String summary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_info.time
     *
     * @mbg.generated Sun Jan 10 16:07:36 GMT+08:00 2021
     */
    private Integer time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_info.price
     *
     * @mbg.generated Sun Jan 10 16:07:36 GMT+08:00 2021
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_info.image
     *
     * @mbg.generated Sun Jan 10 16:07:36 GMT+08:00 2021
     */
    private String image;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_info.level
     *
     * @mbg.generated Sun Jan 10 16:07:36 GMT+08:00 2021
     */
    private String level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_info.charge
     *
     * @mbg.generated Sun Jan 10 16:07:36 GMT+08:00 2021
     */
    private String charge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_info.status
     *
     * @mbg.generated Sun Jan 10 16:07:36 GMT+08:00 2021
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_info.enroll
     *
     * @mbg.generated Sun Jan 10 16:07:36 GMT+08:00 2021
     */
    private Integer enroll;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_info.sort
     *
     * @mbg.generated Sun Jan 10 16:07:36 GMT+08:00 2021
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_info.created_at
     *
     * @mbg.generated Sun Jan 10 16:07:36 GMT+08:00 2021
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_info.updated_at
     *
     * @mbg.generated Sun Jan 10 16:07:36 GMT+08:00 2021
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_info.id
     *
     * @return the value of course_info.id
     *
     * @mbg.generated Sun Jan 10 16:07:36 GMT+08:00 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_info.id
     *
     * @param id the value for course_info.id
     *
     * @mbg.generated Sun Jan 10 16:07:36 GMT+08:00 2021
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_info.name
     *
     * @return the value of course_info.name
     *
     * @mbg.generated Sun Jan 10 16:07:36 GMT+08:00 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_info.name
     *
     * @param name the value for course_info.name
     *
     * @mbg.generated Sun Jan 10 16:07:36 GMT+08:00 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_info.summary
     *
     * @return the value of course_info.summary
     *
     * @mbg.generated Sun Jan 10 16:07:36 GMT+08:00 2021
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_info.summary
     *
     * @param summary the value for course_info.summary
     *
     * @mbg.generated Sun Jan 10 16:07:36 GMT+08:00 2021
     */
    public void setSummary(String summary) {
        this.summary = summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_info.time
     *
     * @return the value of course_info.time
     *
     * @mbg.generated Sun Jan 10 16:07:36 GMT+08:00 2021
     */
    public Integer getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_info.time
     *
     * @param time the value for course_info.time
     *
     * @mbg.generated Sun Jan 10 16:07:36 GMT+08:00 2021
     */
    public void setTime(Integer time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_info.price
     *
     * @return the value of course_info.price
     *
     * @mbg.generated Sun Jan 10 16:07:36 GMT+08:00 2021
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_info.price
     *
     * @param price the value for course_info.price
     *
     * @mbg.generated Sun Jan 10 16:07:36 GMT+08:00 2021
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_info.image
     *
     * @return the value of course_info.image
     *
     * @mbg.generated Sun Jan 10 16:07:36 GMT+08:00 2021
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_info.image
     *
     * @param image the value for course_info.image
     *
     * @mbg.generated Sun Jan 10 16:07:36 GMT+08:00 2021
     */
    public void setImage(String image) {
        this.image = image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_info.level
     *
     * @return the value of course_info.level
     *
     * @mbg.generated Sun Jan 10 16:07:36 GMT+08:00 2021
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_info.level
     *
     * @param level the value for course_info.level
     *
     * @mbg.generated Sun Jan 10 16:07:36 GMT+08:00 2021
     */
    public void setLevel(String level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_info.charge
     *
     * @return the value of course_info.charge
     *
     * @mbg.generated Sun Jan 10 16:07:36 GMT+08:00 2021
     */
    public String getCharge() {
        return charge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_info.charge
     *
     * @param charge the value for course_info.charge
     *
     * @mbg.generated Sun Jan 10 16:07:36 GMT+08:00 2021
     */
    public void setCharge(String charge) {
        this.charge = charge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_info.status
     *
     * @return the value of course_info.status
     *
     * @mbg.generated Sun Jan 10 16:07:36 GMT+08:00 2021
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_info.status
     *
     * @param status the value for course_info.status
     *
     * @mbg.generated Sun Jan 10 16:07:36 GMT+08:00 2021
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_info.enroll
     *
     * @return the value of course_info.enroll
     *
     * @mbg.generated Sun Jan 10 16:07:36 GMT+08:00 2021
     */
    public Integer getEnroll() {
        return enroll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_info.enroll
     *
     * @param enroll the value for course_info.enroll
     *
     * @mbg.generated Sun Jan 10 16:07:36 GMT+08:00 2021
     */
    public void setEnroll(Integer enroll) {
        this.enroll = enroll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_info.sort
     *
     * @return the value of course_info.sort
     *
     * @mbg.generated Sun Jan 10 16:07:36 GMT+08:00 2021
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_info.sort
     *
     * @param sort the value for course_info.sort
     *
     * @mbg.generated Sun Jan 10 16:07:36 GMT+08:00 2021
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_info.created_at
     *
     * @return the value of course_info.created_at
     *
     * @mbg.generated Sun Jan 10 16:07:36 GMT+08:00 2021
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_info.created_at
     *
     * @param createdAt the value for course_info.created_at
     *
     * @mbg.generated Sun Jan 10 16:07:36 GMT+08:00 2021
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_info.updated_at
     *
     * @return the value of course_info.updated_at
     *
     * @mbg.generated Sun Jan 10 16:07:36 GMT+08:00 2021
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_info.updated_at
     *
     * @param updatedAt the value for course_info.updated_at
     *
     * @mbg.generated Sun Jan 10 16:07:36 GMT+08:00 2021
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}