package com.jiac.server.domain;

public class CourseCategory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_category.id
     *
     * @mbg.generated Wed Jan 13 13:48:49 GMT+08:00 2021
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_category.course_id
     *
     * @mbg.generated Wed Jan 13 13:48:49 GMT+08:00 2021
     */
    private String courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_category.category_id
     *
     * @mbg.generated Wed Jan 13 13:48:49 GMT+08:00 2021
     */
    private String categoryId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_category.id
     *
     * @return the value of course_category.id
     *
     * @mbg.generated Wed Jan 13 13:48:49 GMT+08:00 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_category.id
     *
     * @param id the value for course_category.id
     *
     * @mbg.generated Wed Jan 13 13:48:49 GMT+08:00 2021
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_category.course_id
     *
     * @return the value of course_category.course_id
     *
     * @mbg.generated Wed Jan 13 13:48:49 GMT+08:00 2021
     */
    public String getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_category.course_id
     *
     * @param courseId the value for course_category.course_id
     *
     * @mbg.generated Wed Jan 13 13:48:49 GMT+08:00 2021
     */
    public void setCourseId(String courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_category.category_id
     *
     * @return the value of course_category.category_id
     *
     * @mbg.generated Wed Jan 13 13:48:49 GMT+08:00 2021
     */
    public String getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_category.category_id
     *
     * @param categoryId the value for course_category.category_id
     *
     * @mbg.generated Wed Jan 13 13:48:49 GMT+08:00 2021
     */
    public void setCategoryId(String categoryId) {
        this.categoryId = categoryId;
    }
}