package com.jiac.server.domain;

import java.util.Date;

public class File {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.id
     *
     * @mbg.generated Fri Jan 15 09:11:35 GMT+08:00 2021
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.path
     *
     * @mbg.generated Fri Jan 15 09:11:35 GMT+08:00 2021
     */
    private String path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.name
     *
     * @mbg.generated Fri Jan 15 09:11:35 GMT+08:00 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.suffix
     *
     * @mbg.generated Fri Jan 15 09:11:35 GMT+08:00 2021
     */
    private String suffix;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.size
     *
     * @mbg.generated Fri Jan 15 09:11:35 GMT+08:00 2021
     */
    private Integer size;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.use
     *
     * @mbg.generated Fri Jan 15 09:11:35 GMT+08:00 2021
     */
    private String use;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.created_at
     *
     * @mbg.generated Fri Jan 15 09:11:35 GMT+08:00 2021
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.updated_at
     *
     * @mbg.generated Fri Jan 15 09:11:35 GMT+08:00 2021
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.shard_index
     *
     * @mbg.generated Fri Jan 15 09:11:35 GMT+08:00 2021
     */
    private Integer shardIndex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.shard_size
     *
     * @mbg.generated Fri Jan 15 09:11:35 GMT+08:00 2021
     */
    private Integer shardSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.shard_total
     *
     * @mbg.generated Fri Jan 15 09:11:35 GMT+08:00 2021
     */
    private Integer shardTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.key
     *
     * @mbg.generated Fri Jan 15 09:11:35 GMT+08:00 2021
     */
    private String key;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.id
     *
     * @return the value of file.id
     *
     * @mbg.generated Fri Jan 15 09:11:35 GMT+08:00 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.id
     *
     * @param id the value for file.id
     *
     * @mbg.generated Fri Jan 15 09:11:35 GMT+08:00 2021
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.path
     *
     * @return the value of file.path
     *
     * @mbg.generated Fri Jan 15 09:11:35 GMT+08:00 2021
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.path
     *
     * @param path the value for file.path
     *
     * @mbg.generated Fri Jan 15 09:11:35 GMT+08:00 2021
     */
    public void setPath(String path) {
        this.path = path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.name
     *
     * @return the value of file.name
     *
     * @mbg.generated Fri Jan 15 09:11:35 GMT+08:00 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.name
     *
     * @param name the value for file.name
     *
     * @mbg.generated Fri Jan 15 09:11:35 GMT+08:00 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.suffix
     *
     * @return the value of file.suffix
     *
     * @mbg.generated Fri Jan 15 09:11:35 GMT+08:00 2021
     */
    public String getSuffix() {
        return suffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.suffix
     *
     * @param suffix the value for file.suffix
     *
     * @mbg.generated Fri Jan 15 09:11:35 GMT+08:00 2021
     */
    public void setSuffix(String suffix) {
        this.suffix = suffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.size
     *
     * @return the value of file.size
     *
     * @mbg.generated Fri Jan 15 09:11:35 GMT+08:00 2021
     */
    public Integer getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.size
     *
     * @param size the value for file.size
     *
     * @mbg.generated Fri Jan 15 09:11:35 GMT+08:00 2021
     */
    public void setSize(Integer size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.use
     *
     * @return the value of file.use
     *
     * @mbg.generated Fri Jan 15 09:11:35 GMT+08:00 2021
     */
    public String getUse() {
        return use;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.use
     *
     * @param use the value for file.use
     *
     * @mbg.generated Fri Jan 15 09:11:35 GMT+08:00 2021
     */
    public void setUse(String use) {
        this.use = use;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.created_at
     *
     * @return the value of file.created_at
     *
     * @mbg.generated Fri Jan 15 09:11:35 GMT+08:00 2021
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.created_at
     *
     * @param createdAt the value for file.created_at
     *
     * @mbg.generated Fri Jan 15 09:11:35 GMT+08:00 2021
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.updated_at
     *
     * @return the value of file.updated_at
     *
     * @mbg.generated Fri Jan 15 09:11:35 GMT+08:00 2021
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.updated_at
     *
     * @param updatedAt the value for file.updated_at
     *
     * @mbg.generated Fri Jan 15 09:11:35 GMT+08:00 2021
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.shard_index
     *
     * @return the value of file.shard_index
     *
     * @mbg.generated Fri Jan 15 09:11:35 GMT+08:00 2021
     */
    public Integer getShardIndex() {
        return shardIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.shard_index
     *
     * @param shardIndex the value for file.shard_index
     *
     * @mbg.generated Fri Jan 15 09:11:35 GMT+08:00 2021
     */
    public void setShardIndex(Integer shardIndex) {
        this.shardIndex = shardIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.shard_size
     *
     * @return the value of file.shard_size
     *
     * @mbg.generated Fri Jan 15 09:11:35 GMT+08:00 2021
     */
    public Integer getShardSize() {
        return shardSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.shard_size
     *
     * @param shardSize the value for file.shard_size
     *
     * @mbg.generated Fri Jan 15 09:11:35 GMT+08:00 2021
     */
    public void setShardSize(Integer shardSize) {
        this.shardSize = shardSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.shard_total
     *
     * @return the value of file.shard_total
     *
     * @mbg.generated Fri Jan 15 09:11:35 GMT+08:00 2021
     */
    public Integer getShardTotal() {
        return shardTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.shard_total
     *
     * @param shardTotal the value for file.shard_total
     *
     * @mbg.generated Fri Jan 15 09:11:35 GMT+08:00 2021
     */
    public void setShardTotal(Integer shardTotal) {
        this.shardTotal = shardTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.key
     *
     * @return the value of file.key
     *
     * @mbg.generated Fri Jan 15 09:11:35 GMT+08:00 2021
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.key
     *
     * @param key the value for file.key
     *
     * @mbg.generated Fri Jan 15 09:11:35 GMT+08:00 2021
     */
    public void setKey(String key) {
        this.key = key;
    }
}