package com.jiac.server.domain;

public class Resource {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.id
     *
     * @mbg.generated Mon Jan 18 10:29:25 GMT+08:00 2021
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.name
     *
     * @mbg.generated Mon Jan 18 10:29:25 GMT+08:00 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.page
     *
     * @mbg.generated Mon Jan 18 10:29:25 GMT+08:00 2021
     */
    private String page;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.request
     *
     * @mbg.generated Mon Jan 18 10:29:25 GMT+08:00 2021
     */
    private String request;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.parent
     *
     * @mbg.generated Mon Jan 18 10:29:25 GMT+08:00 2021
     */
    private String parent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.id
     *
     * @return the value of resource.id
     *
     * @mbg.generated Mon Jan 18 10:29:25 GMT+08:00 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.id
     *
     * @param id the value for resource.id
     *
     * @mbg.generated Mon Jan 18 10:29:25 GMT+08:00 2021
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.name
     *
     * @return the value of resource.name
     *
     * @mbg.generated Mon Jan 18 10:29:25 GMT+08:00 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.name
     *
     * @param name the value for resource.name
     *
     * @mbg.generated Mon Jan 18 10:29:25 GMT+08:00 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.page
     *
     * @return the value of resource.page
     *
     * @mbg.generated Mon Jan 18 10:29:25 GMT+08:00 2021
     */
    public String getPage() {
        return page;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.page
     *
     * @param page the value for resource.page
     *
     * @mbg.generated Mon Jan 18 10:29:25 GMT+08:00 2021
     */
    public void setPage(String page) {
        this.page = page;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.request
     *
     * @return the value of resource.request
     *
     * @mbg.generated Mon Jan 18 10:29:25 GMT+08:00 2021
     */
    public String getRequest() {
        return request;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.request
     *
     * @param request the value for resource.request
     *
     * @mbg.generated Mon Jan 18 10:29:25 GMT+08:00 2021
     */
    public void setRequest(String request) {
        this.request = request;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.parent
     *
     * @return the value of resource.parent
     *
     * @mbg.generated Mon Jan 18 10:29:25 GMT+08:00 2021
     */
    public String getParent() {
        return parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.parent
     *
     * @param parent the value for resource.parent
     *
     * @mbg.generated Mon Jan 18 10:29:25 GMT+08:00 2021
     */
    public void setParent(String parent) {
        this.parent = parent;
    }
}