package com.jiac.server.domain;

public class RoleUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_user.id
     *
     * @mbg.generated Mon Jan 18 10:58:56 GMT+08:00 2021
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_user.role_id
     *
     * @mbg.generated Mon Jan 18 10:58:56 GMT+08:00 2021
     */
    private String roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_user.user_id
     *
     * @mbg.generated Mon Jan 18 10:58:56 GMT+08:00 2021
     */
    private String userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_user.id
     *
     * @return the value of role_user.id
     *
     * @mbg.generated Mon Jan 18 10:58:56 GMT+08:00 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_user.id
     *
     * @param id the value for role_user.id
     *
     * @mbg.generated Mon Jan 18 10:58:56 GMT+08:00 2021
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_user.role_id
     *
     * @return the value of role_user.role_id
     *
     * @mbg.generated Mon Jan 18 10:58:56 GMT+08:00 2021
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_user.role_id
     *
     * @param roleId the value for role_user.role_id
     *
     * @mbg.generated Mon Jan 18 10:58:56 GMT+08:00 2021
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_user.user_id
     *
     * @return the value of role_user.user_id
     *
     * @mbg.generated Mon Jan 18 10:58:56 GMT+08:00 2021
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_user.user_id
     *
     * @param userId the value for role_user.user_id
     *
     * @mbg.generated Mon Jan 18 10:58:56 GMT+08:00 2021
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }
}