package com.jiac.server.domain;

public class RoleResource {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_resource.id
     *
     * @mbg.generated Mon Jan 18 10:52:51 GMT+08:00 2021
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_resource.role_id
     *
     * @mbg.generated Mon Jan 18 10:52:51 GMT+08:00 2021
     */
    private String roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_resource.resource_id
     *
     * @mbg.generated Mon Jan 18 10:52:51 GMT+08:00 2021
     */
    private String resourceId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_resource.id
     *
     * @return the value of role_resource.id
     *
     * @mbg.generated Mon Jan 18 10:52:51 GMT+08:00 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_resource.id
     *
     * @param id the value for role_resource.id
     *
     * @mbg.generated Mon Jan 18 10:52:51 GMT+08:00 2021
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_resource.role_id
     *
     * @return the value of role_resource.role_id
     *
     * @mbg.generated Mon Jan 18 10:52:51 GMT+08:00 2021
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_resource.role_id
     *
     * @param roleId the value for role_resource.role_id
     *
     * @mbg.generated Mon Jan 18 10:52:51 GMT+08:00 2021
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_resource.resource_id
     *
     * @return the value of role_resource.resource_id
     *
     * @mbg.generated Mon Jan 18 10:52:51 GMT+08:00 2021
     */
    public String getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_resource.resource_id
     *
     * @param resourceId the value for role_resource.resource_id
     *
     * @mbg.generated Mon Jan 18 10:52:51 GMT+08:00 2021
     */
    public void setResourceId(String resourceId) {
        this.resourceId = resourceId;
    }
}