package com.jiac.server.domain;

import java.util.Date;

public class Section {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column section.id
     *
     * @mbg.generated Sun Jan 10 09:24:33 GMT+08:00 2021
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column section.title
     *
     * @mbg.generated Sun Jan 10 09:24:33 GMT+08:00 2021
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column section.course_id
     *
     * @mbg.generated Sun Jan 10 09:24:33 GMT+08:00 2021
     */
    private String courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column section.chapter_id
     *
     * @mbg.generated Sun Jan 10 09:24:33 GMT+08:00 2021
     */
    private String chapterId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column section.video
     *
     * @mbg.generated Sun Jan 10 09:24:33 GMT+08:00 2021
     */
    private String video;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column section.time
     *
     * @mbg.generated Sun Jan 10 09:24:33 GMT+08:00 2021
     */
    private Integer time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column section.charge
     *
     * @mbg.generated Sun Jan 10 09:24:33 GMT+08:00 2021
     */
    private String charge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column section.sort
     *
     * @mbg.generated Sun Jan 10 09:24:33 GMT+08:00 2021
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column section.created_at
     *
     * @mbg.generated Sun Jan 10 09:24:33 GMT+08:00 2021
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column section.updated_at
     *
     * @mbg.generated Sun Jan 10 09:24:33 GMT+08:00 2021
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column section.id
     *
     * @return the value of section.id
     *
     * @mbg.generated Sun Jan 10 09:24:33 GMT+08:00 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column section.id
     *
     * @param id the value for section.id
     *
     * @mbg.generated Sun Jan 10 09:24:33 GMT+08:00 2021
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column section.title
     *
     * @return the value of section.title
     *
     * @mbg.generated Sun Jan 10 09:24:33 GMT+08:00 2021
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column section.title
     *
     * @param title the value for section.title
     *
     * @mbg.generated Sun Jan 10 09:24:33 GMT+08:00 2021
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column section.course_id
     *
     * @return the value of section.course_id
     *
     * @mbg.generated Sun Jan 10 09:24:33 GMT+08:00 2021
     */
    public String getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column section.course_id
     *
     * @param courseId the value for section.course_id
     *
     * @mbg.generated Sun Jan 10 09:24:33 GMT+08:00 2021
     */
    public void setCourseId(String courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column section.chapter_id
     *
     * @return the value of section.chapter_id
     *
     * @mbg.generated Sun Jan 10 09:24:33 GMT+08:00 2021
     */
    public String getChapterId() {
        return chapterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column section.chapter_id
     *
     * @param chapterId the value for section.chapter_id
     *
     * @mbg.generated Sun Jan 10 09:24:33 GMT+08:00 2021
     */
    public void setChapterId(String chapterId) {
        this.chapterId = chapterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column section.video
     *
     * @return the value of section.video
     *
     * @mbg.generated Sun Jan 10 09:24:33 GMT+08:00 2021
     */
    public String getVideo() {
        return video;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column section.video
     *
     * @param video the value for section.video
     *
     * @mbg.generated Sun Jan 10 09:24:33 GMT+08:00 2021
     */
    public void setVideo(String video) {
        this.video = video;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column section.time
     *
     * @return the value of section.time
     *
     * @mbg.generated Sun Jan 10 09:24:33 GMT+08:00 2021
     */
    public Integer getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column section.time
     *
     * @param time the value for section.time
     *
     * @mbg.generated Sun Jan 10 09:24:33 GMT+08:00 2021
     */
    public void setTime(Integer time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column section.charge
     *
     * @return the value of section.charge
     *
     * @mbg.generated Sun Jan 10 09:24:33 GMT+08:00 2021
     */
    public String getCharge() {
        return charge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column section.charge
     *
     * @param charge the value for section.charge
     *
     * @mbg.generated Sun Jan 10 09:24:33 GMT+08:00 2021
     */
    public void setCharge(String charge) {
        this.charge = charge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column section.sort
     *
     * @return the value of section.sort
     *
     * @mbg.generated Sun Jan 10 09:24:33 GMT+08:00 2021
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column section.sort
     *
     * @param sort the value for section.sort
     *
     * @mbg.generated Sun Jan 10 09:24:33 GMT+08:00 2021
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column section.created_at
     *
     * @return the value of section.created_at
     *
     * @mbg.generated Sun Jan 10 09:24:33 GMT+08:00 2021
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column section.created_at
     *
     * @param createdAt the value for section.created_at
     *
     * @mbg.generated Sun Jan 10 09:24:33 GMT+08:00 2021
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column section.updated_at
     *
     * @return the value of section.updated_at
     *
     * @mbg.generated Sun Jan 10 09:24:33 GMT+08:00 2021
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column section.updated_at
     *
     * @param updatedAt the value for section.updated_at
     *
     * @mbg.generated Sun Jan 10 09:24:33 GMT+08:00 2021
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}