package com.jiac.server.domain;

public class Teacher {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.id
     *
     * @mbg.generated Wed Jan 13 15:03:30 GMT+08:00 2021
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.name
     *
     * @mbg.generated Wed Jan 13 15:03:30 GMT+08:00 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.nickname
     *
     * @mbg.generated Wed Jan 13 15:03:30 GMT+08:00 2021
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.image
     *
     * @mbg.generated Wed Jan 13 15:03:30 GMT+08:00 2021
     */
    private String image;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.position
     *
     * @mbg.generated Wed Jan 13 15:03:30 GMT+08:00 2021
     */
    private String position;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.motto
     *
     * @mbg.generated Wed Jan 13 15:03:30 GMT+08:00 2021
     */
    private String motto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.intro
     *
     * @mbg.generated Wed Jan 13 15:03:30 GMT+08:00 2021
     */
    private String intro;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.id
     *
     * @return the value of teacher.id
     *
     * @mbg.generated Wed Jan 13 15:03:30 GMT+08:00 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.id
     *
     * @param id the value for teacher.id
     *
     * @mbg.generated Wed Jan 13 15:03:30 GMT+08:00 2021
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.name
     *
     * @return the value of teacher.name
     *
     * @mbg.generated Wed Jan 13 15:03:30 GMT+08:00 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.name
     *
     * @param name the value for teacher.name
     *
     * @mbg.generated Wed Jan 13 15:03:30 GMT+08:00 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.nickname
     *
     * @return the value of teacher.nickname
     *
     * @mbg.generated Wed Jan 13 15:03:30 GMT+08:00 2021
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.nickname
     *
     * @param nickname the value for teacher.nickname
     *
     * @mbg.generated Wed Jan 13 15:03:30 GMT+08:00 2021
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.image
     *
     * @return the value of teacher.image
     *
     * @mbg.generated Wed Jan 13 15:03:30 GMT+08:00 2021
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.image
     *
     * @param image the value for teacher.image
     *
     * @mbg.generated Wed Jan 13 15:03:30 GMT+08:00 2021
     */
    public void setImage(String image) {
        this.image = image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.position
     *
     * @return the value of teacher.position
     *
     * @mbg.generated Wed Jan 13 15:03:30 GMT+08:00 2021
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.position
     *
     * @param position the value for teacher.position
     *
     * @mbg.generated Wed Jan 13 15:03:30 GMT+08:00 2021
     */
    public void setPosition(String position) {
        this.position = position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.motto
     *
     * @return the value of teacher.motto
     *
     * @mbg.generated Wed Jan 13 15:03:30 GMT+08:00 2021
     */
    public String getMotto() {
        return motto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.motto
     *
     * @param motto the value for teacher.motto
     *
     * @mbg.generated Wed Jan 13 15:03:30 GMT+08:00 2021
     */
    public void setMotto(String motto) {
        this.motto = motto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.intro
     *
     * @return the value of teacher.intro
     *
     * @mbg.generated Wed Jan 13 15:03:30 GMT+08:00 2021
     */
    public String getIntro() {
        return intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.intro
     *
     * @param intro the value for teacher.intro
     *
     * @mbg.generated Wed Jan 13 15:03:30 GMT+08:00 2021
     */
    public void setIntro(String intro) {
        this.intro = intro;
    }
}