package com.jiac.server.domain;

public class UserAdmin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_admin.id
     *
     * @mbg.generated Sat Jan 16 09:09:18 GMT+08:00 2021
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_admin.login_name
     *
     * @mbg.generated Sat Jan 16 09:09:18 GMT+08:00 2021
     */
    private String loginName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_admin.name
     *
     * @mbg.generated Sat Jan 16 09:09:18 GMT+08:00 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_admin.password
     *
     * @mbg.generated Sat Jan 16 09:09:18 GMT+08:00 2021
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_admin.id
     *
     * @return the value of user_admin.id
     *
     * @mbg.generated Sat Jan 16 09:09:18 GMT+08:00 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_admin.id
     *
     * @param id the value for user_admin.id
     *
     * @mbg.generated Sat Jan 16 09:09:18 GMT+08:00 2021
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_admin.login_name
     *
     * @return the value of user_admin.login_name
     *
     * @mbg.generated Sat Jan 16 09:09:18 GMT+08:00 2021
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_admin.login_name
     *
     * @param loginName the value for user_admin.login_name
     *
     * @mbg.generated Sat Jan 16 09:09:18 GMT+08:00 2021
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_admin.name
     *
     * @return the value of user_admin.name
     *
     * @mbg.generated Sat Jan 16 09:09:18 GMT+08:00 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_admin.name
     *
     * @param name the value for user_admin.name
     *
     * @mbg.generated Sat Jan 16 09:09:18 GMT+08:00 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_admin.password
     *
     * @return the value of user_admin.password
     *
     * @mbg.generated Sat Jan 16 09:09:18 GMT+08:00 2021
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_admin.password
     *
     * @param password the value for user_admin.password
     *
     * @mbg.generated Sat Jan 16 09:09:18 GMT+08:00 2021
     */
    public void setPassword(String password) {
        this.password = password;
    }
}