package com.jiac.server.mapper;

import com.jiac.server.domain.CourseContentFile;
import com.jiac.server.domain.CourseContentFileExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CourseContentFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_content_file
     *
     * @mbg.generated Thu Jan 14 13:29:37 GMT+08:00 2021
     */
    long countByExample(CourseContentFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_content_file
     *
     * @mbg.generated Thu Jan 14 13:29:37 GMT+08:00 2021
     */
    int deleteByExample(CourseContentFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_content_file
     *
     * @mbg.generated Thu Jan 14 13:29:37 GMT+08:00 2021
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_content_file
     *
     * @mbg.generated Thu Jan 14 13:29:37 GMT+08:00 2021
     */
    int insert(CourseContentFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_content_file
     *
     * @mbg.generated Thu Jan 14 13:29:37 GMT+08:00 2021
     */
    int insertSelective(CourseContentFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_content_file
     *
     * @mbg.generated Thu Jan 14 13:29:37 GMT+08:00 2021
     */
    List<CourseContentFile> selectByExample(CourseContentFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_content_file
     *
     * @mbg.generated Thu Jan 14 13:29:37 GMT+08:00 2021
     */
    CourseContentFile selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_content_file
     *
     * @mbg.generated Thu Jan 14 13:29:37 GMT+08:00 2021
     */
    int updateByExampleSelective(@Param("record") CourseContentFile record, @Param("example") CourseContentFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_content_file
     *
     * @mbg.generated Thu Jan 14 13:29:37 GMT+08:00 2021
     */
    int updateByExample(@Param("record") CourseContentFile record, @Param("example") CourseContentFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_content_file
     *
     * @mbg.generated Thu Jan 14 13:29:37 GMT+08:00 2021
     */
    int updateByPrimaryKeySelective(CourseContentFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_content_file
     *
     * @mbg.generated Thu Jan 14 13:29:37 GMT+08:00 2021
     */
    int updateByPrimaryKey(CourseContentFile record);
}