package com.jiac.server.mapper;

import com.jiac.server.domain.CourseContent;
import com.jiac.server.domain.CourseContentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CourseContentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_content
     *
     * @mbg.generated Wed Jan 13 14:23:45 GMT+08:00 2021
     */
    long countByExample(CourseContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_content
     *
     * @mbg.generated Wed Jan 13 14:23:45 GMT+08:00 2021
     */
    int deleteByExample(CourseContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_content
     *
     * @mbg.generated Wed Jan 13 14:23:45 GMT+08:00 2021
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_content
     *
     * @mbg.generated Wed Jan 13 14:23:45 GMT+08:00 2021
     */
    int insert(CourseContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_content
     *
     * @mbg.generated Wed Jan 13 14:23:45 GMT+08:00 2021
     */
    int insertSelective(CourseContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_content
     *
     * @mbg.generated Wed Jan 13 14:23:45 GMT+08:00 2021
     */
    List<CourseContent> selectByExampleWithBLOBs(CourseContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_content
     *
     * @mbg.generated Wed Jan 13 14:23:45 GMT+08:00 2021
     */
    List<CourseContent> selectByExample(CourseContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_content
     *
     * @mbg.generated Wed Jan 13 14:23:45 GMT+08:00 2021
     */
    CourseContent selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_content
     *
     * @mbg.generated Wed Jan 13 14:23:45 GMT+08:00 2021
     */
    int updateByExampleSelective(@Param("record") CourseContent record, @Param("example") CourseContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_content
     *
     * @mbg.generated Wed Jan 13 14:23:45 GMT+08:00 2021
     */
    int updateByExampleWithBLOBs(@Param("record") CourseContent record, @Param("example") CourseContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_content
     *
     * @mbg.generated Wed Jan 13 14:23:45 GMT+08:00 2021
     */
    int updateByExample(@Param("record") CourseContent record, @Param("example") CourseContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_content
     *
     * @mbg.generated Wed Jan 13 14:23:45 GMT+08:00 2021
     */
    int updateByPrimaryKeySelective(CourseContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_content
     *
     * @mbg.generated Wed Jan 13 14:23:45 GMT+08:00 2021
     */
    int updateByPrimaryKeyWithBLOBs(CourseContent record);
}