package com.jiac.server.mapper;

import com.jiac.server.domain.Resource;
import com.jiac.server.domain.ResourceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;


public interface ResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbg.generated Mon Jan 18 10:29:25 GMT+08:00 2021
     */
    long countByExample(ResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbg.generated Mon Jan 18 10:29:25 GMT+08:00 2021
     */
    int deleteByExample(ResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbg.generated Mon Jan 18 10:29:25 GMT+08:00 2021
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbg.generated Mon Jan 18 10:29:25 GMT+08:00 2021
     */
    int insert(Resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbg.generated Mon Jan 18 10:29:25 GMT+08:00 2021
     */
    int insertSelective(Resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbg.generated Mon Jan 18 10:29:25 GMT+08:00 2021
     */
    List<Resource> selectByExample(ResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbg.generated Mon Jan 18 10:29:25 GMT+08:00 2021
     */
    Resource selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbg.generated Mon Jan 18 10:29:25 GMT+08:00 2021
     */
    int updateByExampleSelective(@Param("record") Resource record, @Param("example") ResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbg.generated Mon Jan 18 10:29:25 GMT+08:00 2021
     */
    int updateByExample(@Param("record") Resource record, @Param("example") ResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbg.generated Mon Jan 18 10:29:25 GMT+08:00 2021
     */
    int updateByPrimaryKeySelective(Resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbg.generated Mon Jan 18 10:29:25 GMT+08:00 2021
     */
    int updateByPrimaryKey(Resource record);
}