package com.jiac.server.mapper;

import com.jiac.server.domain.UserAdmin;
import com.jiac.server.domain.UserAdminExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_admin
     *
     * @mbg.generated Sat Jan 16 09:09:18 GMT+08:00 2021
     */
    long countByExample(UserAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_admin
     *
     * @mbg.generated Sat Jan 16 09:09:18 GMT+08:00 2021
     */
    int deleteByExample(UserAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_admin
     *
     * @mbg.generated Sat Jan 16 09:09:18 GMT+08:00 2021
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_admin
     *
     * @mbg.generated Sat Jan 16 09:09:18 GMT+08:00 2021
     */
    int insert(UserAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_admin
     *
     * @mbg.generated Sat Jan 16 09:09:18 GMT+08:00 2021
     */
    int insertSelective(UserAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_admin
     *
     * @mbg.generated Sat Jan 16 09:09:18 GMT+08:00 2021
     */
    List<UserAdmin> selectByExample(UserAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_admin
     *
     * @mbg.generated Sat Jan 16 09:09:18 GMT+08:00 2021
     */
    UserAdmin selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_admin
     *
     * @mbg.generated Sat Jan 16 09:09:18 GMT+08:00 2021
     */
    int updateByExampleSelective(@Param("record") UserAdmin record, @Param("example") UserAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_admin
     *
     * @mbg.generated Sat Jan 16 09:09:18 GMT+08:00 2021
     */
    int updateByExample(@Param("record") UserAdmin record, @Param("example") UserAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_admin
     *
     * @mbg.generated Sat Jan 16 09:09:18 GMT+08:00 2021
     */
    int updateByPrimaryKeySelective(UserAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_admin
     *
     * @mbg.generated Sat Jan 16 09:09:18 GMT+08:00 2021
     */
    int updateByPrimaryKey(UserAdmin record);
}